# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fx-test',
                'doc_host': 'https://dmitryhits.github.io',
                'git_url': 'https://github.com/dmitryhits/fx-test',
                'lib_path': 'fx_test'},
  'syms': {'fx_test.core': {'fx_test.core.foo': ('core.html#foo', 'fx_test/core.py')}}}
